language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ckVMNahlVTLpwhDEptqaKqmUsmX0U8AXjiGofYFr7DqQQ+/rnwGReJ8kZBUKSTEOMKZ6qZM2V5E+hZFt2psd9N2YoVgWdUCt3UVgsq5VT5nyJ9KFNUlSIfp0qbuL3TMGIaZv+8pUevtE6k/yZ/cGT127SQkQcaK3zzKqzBh+qJaSfofHN5gNtGza/pyJwlKua3fB/TRRvOM8C4SWRLtwJI5gxd9arFWEoAMj6sLDt85Vii+NC8VdO1yyla0MNHCJblgWhRjxIHjL0LWqDVUZ+nS2um2dXywxRmVlPLWnH+X9U5vuV8VCA7eqwuM0Ai7Z8XUZR1/ea68gDIpJrEBUnzF9F3TGXlGUcMVPDgBYtl0vBiGFXjwpzpuFDvSkFUK3EBaXhdSiIu67qtcq52A06QKSxeTQn5lBMzWu1mGHOXo5DVxX2K7jOyhGtKq8wY4yz9MHZnjLgnO6Yeo5Ar1K2t5bsQ+yLJTSwvrE3qoR5Wet4Yn30LImoZeCVfb0CBrTwtfDYavdpMC6y3GugHCfljbA5L1Gm4p1VsdiEMdHYLpk7zH8Z4Utceu3iwVoMx3Ue3Ut6puPTMoJzgfVYKWDWoRmVXtQ9CqclW0hXpJtsniyZW9RvqXAvidCsiGciSnXURDoZH3+FsuLJ0XmFs5qs7cbge28CyoUYHyARnVN3j8=
  app: morning-mesa-60247
  on:
    repo: thinkful-ei22/w5d3-brandon
